[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "elissabeth"
version = "2.0.0"
authors = [
  { name="Richard Krieg", email="irkri@irkri.net" },
]
description = "Extended learnable iterated sums signature architecture."
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "torch>=2.12",
    "lightning>=2.6",
    "pydantic>=2",
    "numpy",
    "pyyaml",
    "rich",
]

[project.optional-dependencies]
analysis = ["matplotlib"]
online = ["wandb"]
tropical = ["scipy", "schedulefree"]
test = ["pytest", "scikit-learn"]

[tool.hatch.build.targets.wheel]
packages = ["elissabeth"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[project.urls]
Homepage = "https://github.com/irkri/elissabeth"
Issues = "https://github.com/irkri/elissabeth/issues"